### ISSUE TITLE
failed to import plugin

### ISSUE THREAD

**Issue by sofroniewn** [tlambert03/napari-dv#1]
I'm trying this with https://github.com/napari/napari/pull/937 and am getting the following error - thoughts?

```
PluginError: Failed to import plugin: "dv_reader"
  Cause was: cannot import name 'LayerData' from 'napari.plugins.hook_specifications' (/Users/nsofroniew/GitHub/napari/napari/plugins/hook_specifications.py)
  Please notify the plugin developer:
       name: napari-dv
    version: 0.2.2
      email: talley.lambert@gmail.com
        url: https://github.com/tlambert03/napari-dv
     napari: v0.2.12+93.g4cba0199
```

**Comment by tlambert03** [comment]
Yeah I’m sorta waiting for reader plugin PR to settle before paying attention to this, but if you want me to update it so you can test that out; I’m happy to do that

**Comment by tlambert03** [comment]
I just updated the master branch here so you can use it to test the napari PR again:
`pip install git+git://github.com/tlambert03/napari-dv.git`

**Comment by tlambert03** [comment]
but hey, nice message for a broken plugin right?? ;)

**Comment by sofroniewn** [comment]
works - love it, thanks for updating - and yes - great error message :-)
