### ISSUE TITLE
Example file to demo napari-dv

### ISSUE THREAD

**Issue by GenevieveBuckley** [tlambert03/napari-dv#2]
Talley, is there an example deltavision file I can download and test my plugin installation with?

I thought I might find something to use in the [SCIFIO test images](https://scif.io/images/), but nope.
I could have sworn there was a similar site with test images under the BioFormats umbrella, but I can't find anything like that now.

I've also tried the fies here, but no luck there either: https://github.com/ccpem/mrcfile/tree/master/tests/test_data

The napari-dv plugin is listed under the "Installed plugins" menu in napari, so that's a good sign. But I'd still like to see it in action!

**Comment by tlambert03** [comment]
yeah, there's one in the root of this repo: https://github.com/tlambert03/napari-dv/blob/master/toxo.dv

also: this plugin doesn't use the mrcfile repo you linked ... it uses https://github.com/tlambert03/mrc

(it's a long story... there was some divergence between the formats used for light microscopy and EM a while back, and they're not totally compatible anymore)

**Comment by tlambert03** [comment]
also, btw, I got that image from the [cell image library (deltavision search)](http://www.cellimagelibrary.org/images?advanced_search=Advanced+Search&k=deltavision&zstack=true&public_domain=true&image_search_parms%5Bbiological_process%5D=&image_search_parms%5Bcell_type%5D=&image_search_parms%5Bcell_line%5D=&image_search_parms%5Bfoundational_model_anatomy%5D=&image_search_parms%5Bcellular_component%5D=&image_search_parms%5Bmolecular_function%5D=&image_search_parms%5Bncbi%5D=&image_search_parms%5Bitem_type_bim%5D=&image_search_parms%5Bimage_mode_bim%5D=&image_search_parms%5Bvisualization_methods_bim%5D=&image_search_parms%5Bsource_of_contrast_bim%5D=&image_search_parms%5Brelation_to_intact_cell_bim%5D=&image_search_parms%5Bprocessing_history_bim%5D=&image_search_parms%5Bpreparation_bim%5D=&image_search_parms%5Bparameter_imaged_bim%5D=&image_search_parms%5Bhuman_dev_anatomy%5D=&image_search_parms%5Bhuman_disease%5D=&image_search_parms%5Bmouse_gross_anatomy%5D=&image_search_parms%5Bmouse_pathology%5D=&image_search_parms%5Bplant_growth%5D=&image_search_parms%5Bteleost_anatomy%5D=&image_search_parms%5Bxenopus_anatomy%5D=&image_search_parms%5Bzebrafish_anatomy%5D=)

**Comment by GenevieveBuckley** [comment]
> yeah, there's one in the root of this repo: https://github.com/tlambert03/napari-dv/blob/master/toxo.dv

Oh wow, so there's one right in front of my face? And the only reason I missed it because it was late and I was tired? That's embarrassing! 🤣
